language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
script:
- python setup.py test
- python setup.py sdist
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  username: __token__
  skip_existing: true
  on:
    branch: main
  password:
    secure: wNlQCttdQHj6HGFoEYP5sr/9i4/bcZhPm4zxrtdLYE03vynPDomTT0SWw9jQ/T6qmhoXfusvmiziEOiYZ3qm2OBjgP5NacbzWDh0qxo5y6+LPmTRXKdFJRWXBmolv69bXaFk+2DX4Kjq+F3HUb/oFHC6xI2BaQbTWhY/Em0VwGLHAsIN9yMHOIL1hO0b0+PNNP/NSuJNtE54f0OLt+Ws7hczB3+UyrqLnix219Oe11sB7hsB1ZIV6bWUM0pCurRPP0qEj5iv8Xla++QHe2BdN6VB9ETNoi1znq0e+sjVhqSmuLHxDn4EzV/h31lhdS2jjSAejYrmooIoyKy5U52+piQudmSZKfSUut5mWB9Z3/afdsFAobCMxvtV/u58jy3bUC88tvA+qCzQ38uolFDuYR+prF/9y6jVTVsvkEO7auWjLFoo060/3+Yj5m0KsDUhpT5ComFsRoIj4VCWdBbf6a/jjMpPZcr1mAqTZ/hwd/qOaH+5/MZMw3fKr9fuWRbjXrB4rY7tmMjufywSZ6XzvRQE4djKfkAYKkDA4xjU2H70QES2XuF5nDlhie/Lix3gvMOwhVIc67+xdmFgc2zPqK+RJVzZnA4TciPtQ0wEUAC1dVwuJCVF9MIleTWVFr57tDNTdRDN8jkfofs0qeJwmxMAT8jiaBxXTnAeG6UI2Kg=
